CREATE TABLE IF NOT EXISTS articles (
  id VARCHAR(120) NOT NULL PRIMARY KEY,
  section VARCHAR(20) NOT NULL,
  category VARCHAR(20) NULL,
  articleDate VARCHAR(10) NULL,
  dateLabel VARCHAR(60) NULL,
  source VARCHAR(120) NOT NULL,
  title TEXT NOT NULL,
  url VARCHAR(600) NOT NULL,
  summary TEXT NULL,
  image VARCHAR(600) NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS meta_status (
  id TINYINT NOT NULL PRIMARY KEY DEFAULT 1,
  lastChecked VARCHAR(40) NULL,
  articleCount INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO meta_status (id, lastChecked, articleCount) VALUES (1, NULL, 0)
  ON DUPLICATE KEY UPDATE id = id;
