name: Deploy holasuska FTP-n

on:
  push:
    branches: [main]
  workflow_dispatch: # kézzel is indítható a GitHub "Actions" fülén

jobs:
  ftp-deploy:
    name: FTP feltöltés a tárhelyre
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: Feltöltés FTP-n
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/config.php
            **/README.md
